	TICKER: TJH
	NAME: TransJamaican Highway Limited
  ABOUT: |
    Our core business activity is the development, operation and maintenance 
    of a tolled road network in Jamaica known as the "TransJam Highways" 
    a 49.9km tolled motorway with two distinct corridors:
      T1 43.45km between Kingston and May Pen
      T2 6.5km between Portmore and Kingston
    The motorway corridors are supported by four (4) toll plazas in Portmore, 
    Spanish Town, Vineyards (in Old Harbour), and May Pen.
    In December 2019, TJH became fully Jamaican owned, after having been owned 
    by the two (2) French companies: Bouygues Travaux Publics and VINCI Concessions.

    Its business activity is the development,
    operation and maintenance of a tolled roadway known as "Highway 2000 East-West" under a 
    Concession Agreement with the National Road Operating & Constructing Company ("NROCC") 
    (the "Grantor") made on November 21, 2001 (Amended and Restated on January 28, 2011 
    and January 20, 2020). The concession is for a period of 35 years.
  NOTES: |
    The major costs are the maintenance and operation of the highways.

