	TICKER: SOS
	NAME: Stationery and Office Supplies Limited
  ABOUT: |
    The main activity of the Company is the sale of office furniture, fixtures, stationery and other office
    supplies and the manufacture and sale of books. 
  NOTES: 

