	TICKER: WIG
	NAME: Wigton Windfarm Limited
  ABOUT: |
    Wigton Windfarm Limited (the Company) is incorporated and domiciled in Jamaica. 
    The Company was incorporated on 12 April 2000. It was formerly a wholly owned subsidiary  
    of the Petroleum Corporation of Jamaica.
    The principal activity of the Company is the generation and sale of electricity from wind technology.
  NOTES: |
    Investment in joint operations
    Joint Venture Agreement – Single Project
    On 5 April 2022, the Company and Innovative Energy Company DBA IEC SPEI Limited (formerly IEC SPEI Limited)
    (“IEC”) entered into a joint agreement (as joint operators) for the design, installation, operation, and maintenance
    of green energy solutions for the benefit of third parties who intend to generate green energy for their own
    consumption or to sell power to JPS. As at 31 December 2022, the NMIA project was deemed complete, and the
    Company received its capital investment from the joint venture along with the Company’s share in the net profit
    arising from the project amounting to $5,007,000.
    Joint Venture Agreement – Green Energy Solutions
    The joint arrangement was registered as Wigton-IEC Joint Venture under and in accordance with the Registration
    of Business Names Act on 24 May 2022.
    Wigton’s contribution to capital is $600,000, for a 60% stake in the joint arrangement. The Company holds three
    (3) of the five (5) seats on the joint operations’ board.
    On 13 March 2023, the Wigton-IEC Joint Venture entered into a contract with the Ministry of Agriculture and
    Fisheries (MOAF) for the design, supply, and installation of distributive solar photovoltaic systems (including
    storage) at certain Essex Valley Agriculture Development Project locations which the Company and IEC will
    execute as a project of the Wigton-IEC Joint Venture.
    The agreement between the joint operators provides that on a project-by-project basis, the parties can agree to
    change the contribution percentage. For the MOAF project, the joint operators agreed that the Company’s capital
    contribution would be increased to $990,000 (for a 99% share on the MOAF project).
    The Company’s interest in assets and liabilities of the joint operations are included in the consolidated financial
    statements under their respective asset categories.


