websites:
- https://www.jamaica-gleaner.com/business
- https://www.jamaicaobserver.com/category/business/
prompts:
  rank: |
    This is the home page for a newspaper website
    First, pick out the headlines for the different news stories. 
    Once you have isolated the headlines, rank them from most relevant to least relevant.
    The criteria are:
    - The headline is relevant to the real estate market. (highest weighting)
    - The headline is relevant to the technology market. (medium weighting)
    - The headline is relevant to the stock market. (lowest weighting)

    Return an array of objects with the following properties and nothing else:
    - headline (type: string)
    - priority (type: number)
    - link (type: string)

    The link should be the full URL to the article.
    No two articles should have the same priority.
    The priorities should be in descending order. 
    The highest priority should be 1.
  summarize: |
    Objectively summarize the following text, extracting key 
    financial and business information presented in a bulleted list.
    Each point should be separated by a new line.
    Prioritize facts relevant to real estate professionals and technology
    entrepreneurs. 
    Following the bulleted summary, provide a brief (4-6 sentences) objective 
    analysis explaining the potential economic/business significance of these facts.
    Emphasize the possible strategies or tactics that may be in motion.
    
    Formatting instructions:
    - Your response should be formatted in HTML.
    - The summary and analysis should be formatted as unordered lists <ul> and <li> tags.
    - Use <b> tags to highlight important words instead of '**'
    - The summary and analysis will be placed in a <p> tag, so do not include
      tags like <html>, <body>, <!DOCTYPE html>, or <head> in your response.
    - Omit the word 'html' at the beginning of the response. The entire response
      should be valid html.
    - The analysis section should begin with the word 'Analysis:'
    

