websites:
  - https://www.jamaica-gleaner.com/business
  - https://www.jamaicaobserver.com/category/business/
prompts:
  rank: |
    This is the home page for a newspaper website
    First, pick out the headlines for the different news stories. 
    Once you have isolated the headlines, rank them from most relevant to least relevant.
    The criteria are:
    - The headline is relevant to the real estate market. (highest weighting)
    - The headline is relevant to the technology market. (medium weighting)
    - The headline is relevant to the stock market. (lowest weighting)

    Return an array of objects with the following properties and nothing else:
    - headline (type: string)
    - priority (type: number)
    - link (type: string)

    The link should be the full URL to the article.
    No two articles should have the same priority.
    The priorities should be in descending order. 
    The highest priority should be 1.
  summarize: |
    Summarize the content of this article.
    Distill the content to the most important points. 
    Each important point should be a bullet point and should be a sentence or two.
    Be as dry and factual as possible.
    Information that is pertinent to the following personas should be prioritized:
    - Real estate professionals
    - Technology entrepreneurs/investors
    - Stock market investors

    Once that is completed, append a final paragraph that adds some historical context
    and/or an explanation of why these points are important to the reader.
    This section should be no greater than 4-6 sentences.
higherOrderPrompts:
  chunksThenInstruction: |
    I'm going to send you a series of chunks and then an instruction to execute on the combined chunks.
    The chunks will begin with a header like "CHUNK <number>"
    When you receive the chunks, append them to the previous chunk. Your response should only be "Chunk <number> received".
    The combined chunks will be referred to as "content"
    The instruction will be sent once all the chunks have been uploaded. The instruction should be executed on the "content"
    If you understand, simply respond with the number 7.