FREQUENCY:
	DAILY:
		NEWS:
      - https://jamaica-gleaner.com/business
      - https://www.jamaicaobserver.com/category/business/
      - https://www.jamstockex.com/YYYY/MM/DD/
      - https://icinsider.com/
		STOCK:
      - https://www.jamstockex.com/trading/instruments/?instrument=1600100 # TJH
      - https://www.jamstockex.com/trading/instruments/?instrument=1600087 # WIG
      - https://www.jamstockex.com/trading/instruments/?instrument=1600017 # SOS
	DAY_OF_WEEK:
		TUESDAY:
			- https://jamaica-gleaner.com/article/shipping
	WEEKLY:
		- https://radiojamaicanewsonline.com/business
		- https://our.today/category/business/
	MONTHLY:
	QUARTERLY:
